#!/bin/sh

cat workloads/DataStaxWorkload > DataStaxWorkload-FullInserts.stats
java -cp build/ycsb.jar:db/cassandra-0.7/lib/* com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraClient7 -P workloads/DataStaxWorkload -s -load >> DataStaxWorkload-FullInserts.stats
grep RunTime DataStaxWorkload-FullInserts.stats
grep Throughput DataStaxWorkload-FullInserts.stats
grep AverageLatency DataStaxWorkload-FullInserts.stats

cat workloads/DataStaxWorkload > DataStaxWorkload-FullReads.stats
java -cp build/ycsb.jar:db/cassandra-0.7/lib/* com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraClient7 -P workloads/DataStaxWorkload -s -t >> DataStaxWorkload-FullReads.stats
grep RunTime DataStaxWorkload-FullReads.stats
grep Throughput DataStaxWorkload-FullReads.stats
grep AverageLatency DataStaxWorkload-FullReads.stats

