#!/bin/sh

cat workloads/DataStaxWorkload > DataStaxWorkload-FullInserts-HBase.stats
java -cp build/ycsb.jar:db/hbase/lib/*:db/hbase/conf/ com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.HBaseClient -P workloads/DataStaxWorkload -s -load >> DataStaxWorkload-FullInserts-HBase.stats
grep RunTime DataStaxWorkload-FullInserts-HBase.stats
grep Throughput DataStaxWorkload-FullInserts-HBase.stats
grep AverageLatency DataStaxWorkload-FullInserts-HBase.stats

cat workloads/DataStaxWorkload > DataStaxWorkload-FullReads-HBase.stats
java -cp build/ycsb.jar:db/hbase/lib/*:db/hbase/conf/ com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.HBaseClient -P workloads/DataStaxWorkload -s -t >> DataStaxWorkload-FullReads-HBase.stats
grep RunTime DataStaxWorkload-FullReads-HBase.stats
grep Throughput DataStaxWorkload-FullReads-HBase.stats
grep AverageLatency DataStaxWorkload-FullReads-HBase.stats

